module.exports = require('./detector')
module.exports.profiler = require('./profiler')
module.exports.reducer = require('./reducer')
module.exports.reducers = require('./utils/reducers')
module.exports.trainer = require('./trainer')
module.exports.languageProfiles = require('../data/languageProfiles.json')
